### ISSUE TITLE
deviseのエラー文　日本語

### ISSUE THREAD

**Issue by itasakashogo** [gomamisotest/cd_shop#42]
## railsの日本語化 deviseの日本語化
場所：locales/devise.en.yml
下部に英語で同じ記載あるからそこにこれを貼り付ける

```
errors:
 messages:
  already_confirmed: "は既に登録済みです。ログインしてください"
  confirmation_period_expired: "%{period}以内に確認する必要がありますので、新しくリクエストしてください。"
  expired: "有効期限切れです。新規登録してください。"
  not_found: "は見つかりませんでした。"
  not_locked: "ロックされていません。"
  not_saved:
    one: "エラーにより、この %{resource} を保存できません："
    other: "%{count} 個のエラーにより、この %{resource} を保存できません："
```

参考までに
https://qiita.com/MasatoYoshioka@github/items/8d910e793e7c485403bb

**Comment by itasakashogo** [comment]
修正します。
```
errors:
 messages:
  already_confirmed: "は既に登録済みです。ログインしてください"
  confirmation_period_expired: "%{period}以内に確認する必要がありますので、新しくリクエストしてください。"
  expired: "有効期限切れです。新規登録してください。"
  not_found: "は見つかりませんでした。"
  not_locked: "ロックされていません。"
  not_saved:
    one: "エラーにより、この %{resource} を保存できません："
    other: "%{count} 個のエラーにより、この %{resource} を保存できません："
  taken: "は既に使用されています。"
  blank: "が入力されていません。"
  too_short: "は%{count}文字以上に設定して下さい。"
  too_long: "は%{count}文字以下に設定して下さい。"
  invalid: "は有効でありません。"
  confirmation: "が内容とあっていません。"
```
こうでした。
これだけ入れれば日本語でdeviseにメッセージ可能です
